services:
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus-local
    volumes:
      - ./monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - slice-network

  loki:
    image: grafana/loki:2.9.17
    container_name: loki-local
    ports:
      - "3100:3100"
    networks:
      - slice-network

  promtail:
    image: grafana/promtail:2.9.17
    container_name: promtail-local
    volumes:
      - ./monitor/promtail/promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - slice-network

  grafana:
    image: grafana/grafana:11.4.1
    container_name: grafana-local
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:?GRAFANA_ADMIN_PASSWORD가 .env 파일에 설정되지 않았습니다!}
    depends_on:
      - prometheus
      - loki
    networks:
      - slice-network

networks:
  slice-network:
    external: true
