spring:
  application:
    name: slice-stream-engine

  config:
    import: "optional:file:.env[.properties]"

  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:29092

    consumer:
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "io.slice.stream.engine.*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    # 채팅 메시지 한 줄씩 찍히는 노이즈 차단 (WARN 레벨 이상만 출력)
    io.slice.stream.engine.chat.infrastructure.chzzk.websocket.ChzzkWebSocketListener: WARN
    # 채팅 수집기 연결 로그 차단
    io.slice.stream.engine.chat.infrastructure.kafka.ChzzkChatCollector: WARN
    # (선택 사항) Kafka 컨슈머의 노이즈가 많을 경우 추가
    org.apache.kafka: WARN

chzzk:
  # 1. 치지직 오픈 API (방송 정보 조회 등)
  api:
    base-url: "https://api.chzzk.naver.com"
    live-fetch: "/service/v1/lives"
    live-detail-fetch: "/service/v2/channels/{channelId}/live-detail"

  # 2. 치지직 게임 API (토큰 발급용 - 별도 도메인)
  game-api:
    base-url: "https://comm-api.game.naver.com"

  # 3. 수집할 방송 갯수
  discovery:
    limit: 5

highlight:
  # 피크 채팅 화력 배수
  chat-firepower-multiplier: 3.0
  # 채팅 평균 산출 기간
  range: 2m

api-server:
  host: ${SERVER_HOST}
  path: ${SIGNAL_PATH}
  sync-path: ${SYNC_PATH}
  secret: ${SERVER_SECRET}
  header: ${SERVER_HEADER}
